// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXYl9Vq7EYY1ymdPX9eX_geDjSt2kwwDI',
    appId: '1:633255933198:web:4ccc79e6c1fd607f24935f',
    messagingSenderId: '633255933198',
    projectId: 'cosmicapp-8e6c7',
    authDomain: 'cosmicapp-8e6c7.firebaseapp.com',
    storageBucket: 'cosmicapp-8e6c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4t-oYOoHNEOSdGK98HwkvqD-Y5fR2gUA',
    appId: '1:633255933198:android:237254ffba4baaba24935f',
    messagingSenderId: '633255933198',
    projectId: 'cosmicapp-8e6c7',
    storageBucket: 'cosmicapp-8e6c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-7qDtagxvAk8Uf70BatS_jBs7qPO6rM',
    appId: '1:633255933198:ios:ca02407911193c4924935f',
    messagingSenderId: '633255933198',
    projectId: 'cosmicapp-8e6c7',
    storageBucket: 'cosmicapp-8e6c7.appspot.com',
    iosClientId:
        '633255933198-footjb32d5av7bulk1gvk2jht82i9rjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cosmicExplorer',
  );
}
